spring:
  config:
    import: optional:configserver:http://localhost:8071/
  application:
    name: accounts
 
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final
    username: root
    password: mysql
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

build:
  accounts:
    message: "Hello, Welcome to EazyBytes Accounts related Default APIs!"

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      env:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
info:
  app:
    version: "1.0.0"
    description: "EazyBytes Accounts Service"
    contact:
      email: "L1H5o@example.com"

eureka:
  preferIpAddress: true
  client:
    fetchRegistry: true  # The service will fetch the registry from Eureka
    registerWithEureka: true  # The service will register itself with Eureka
  serviceUrl:
    defaultZone: http://localhost:8070/eureka  # URL of the Eureka server
