spring:
  application:
    name: accounts
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final
    username: root
    password: mysql
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect


build:
  accounts:
    message: "Hello, Welcome to EazyBytes Accounts related Default API's!"


