spring:
  application:
    name: accounts
  profiles:
    active: "qa"  # Activate QA profile
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final_qa  # QA database URL
    username: qa_user  # QA username
    password: qa_password  # QA password
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

build:
  accounts:
    message: "Hello, Welcome to EazyBytes Accounts related QA API's!"  # QA message

contactdetails:
  email: "qa_support@example.com"  # QA support email
  name: "EazyBytes QA Team"  # QA team name
  onCallSupport: "9876543210"  # QA support number

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all management endpoints
