spring:
  application:
    name: accounts
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final
    username: root
    password: mysql
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect


build:
  accounts:
    message: "Hello, Welcome to EazyBytes Accounts related Default API's!"
  contact-details:
    email: "default_support@example.com"  # QA support email
    name: "EazyBytes de Team"  # QA team name
    onCallSupport: "9876543210"  # QA support number

