spring:
  config:
    import: optional:configserver:http://configserver:8071/  # Use Docker service name
  application:
    name: accounts
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver  # Explicit driver class for MySQL
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update  # Adjust to "none" or "validate" for production
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect  # Update for MySQL 8+


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

info:
  app:
    name: "Accounts Service"
    version: "1.0.0"
    description: "EazyBytes Accounts Service"
    contact:
      email: "L1H5o@example.com"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:8070/eureka  # Use Eureka service name
