spring:
  config:
    import: optional:configserver:http://localhost:8071/  # Optional import from config server

  application:
    name: accounts

  profiles:
    active: "default" # Corrected to activate the default profile

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final
    username: root
    password: mysql

  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

build:
  accounts:
    message: "Hello, Welcome to EazyBytes Accounts related Default API'S!"



management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      env:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
info:
  app:
    version: "1.0.0"
    description: "EazyBytes Accounts Service"
    contact:
      email: "L1H5o@example.com"
endpoints:
  shutdown:
    enabled: true
eureka:
  preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
  serviceUrl:
    defaultZone: http://localhost:8070/eureka
RabbitMQ:
  host: localhost
  port: 5672
  username: guest
  password: guest


