spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate.dialect:  org.hibernate.dialect.MySQLDialect
    sql:
      init-mode: always
build:
  cards:
    message: "Hello, Welcome to EazyBytes Accounts realted qa API'S!"
ContactDetails:
  email: "L1H5o@example.com"
  name: "EazyBytes"
  onCallSupport: "1234567890"