spring:
  application:
    name: cards
  
  datasource:
    url: jdbc:mysql://localhost:3306/cardsdb  # QA database URL
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

build:
  cards:
    message: "Hello, Welcome to EazyBytes Cards Realtive related Default API's!"  # QA message

contactdetails:
  email: "support@example.com"  # QA support email
  name: "EazyBytes Def Team"  # QA team name
  onCallSupport: "9876543210"  # QA support number

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all management endpoints
