spring:

  cloud:
    config:
      import-check:
        enabled: false  # Disable import check but still allow Cloud Config use
  application:
    name: cards
  profiles:
    active: "prod"
  config:
    import:
      - optional:configserver:http://localhost:8071/
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final
    username: root
    password: mysql
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect  # Use MySQL8Dialect if MySQL 8.x is used
    sql:
      init-mode: always
server:
  port: 8081

build:
  accounts:
    message: "Hello, Welcome to EazyBytes Accounts related Default API's!"


ContactDetails:
  email: "L1H5o@example.com"
  name: "EazyBytes"
  onCallSupport: "1234567890"
management:
  endpoints:
    web:
      exposure:
        include: "*"
