spring:
  cloud:
    config:
      import-check:
        enabled: false  # Disable import check but still allow Cloud Config us
  application:
    name: accounts
  profiles:
    active: "qa"

  config:
    import:
      - optional:configserver:http://localhost:8071/
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final
    username: root
    password: mysql
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

build:
  accounts:
    message: "Hello, Welcome to EazyBytes Accounts related Default API'S!"

ContactDetails:
  email: "L1H5o@example.com"
  name: "EazyBytes"
  onCallSupport: "1234567890"
management:
  endpoints:
    web:
      exposure:
        include: "*"