spring:
  application:
    name: cards
  profiles:
    active: "default"
  config:
    import:
      - optional:configserver:http://localhost:8071/
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final
    username: root
    password: mysql
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    sql:
      init-mode: always

server:
  port: 8081

build:
  cards:
    message: "Hello, Welcome to EazyBytes Cards related Default API's!"

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      env:
        enabled: true
  endpoint:
    shutdown:
      enabled: true

info:
  app:
    version: "1.0.0"
    description: "EazyBytes Accounts Service"
    contact:
      email: "L1H5o@example.com"

eureka:
  preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
  serviceUrl:
    default: http://localhost:8070/eureka

RabbitMQ:
  host: localhost
  port: 5672
  username: guest
  password: guest
