spring:
  application:
    name: cards
  
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final  # QA database URL
    username: root # QA username
    password: mysql  # QA password
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

build:
  cards:
   message: "Hello, Welcome to EazyBytes cards related dev API'S!"


contactdetails:
  email: "dev_support@example.com"  # QA support email
  name: "EazyBytes DEV Team"  # QA team name
  onCallSupport: "9876543210"  # QA support number

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all management endpoints
