spring:
  application:
    name: cards
  
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_final_qa  # QA database URL
    username: dev_user  # QA username
    password: dev_password  # QA password
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

build:
  accounts:
    message: "Hello, Welcome to EazyBytes Accounts related DEV API's!"  # QA message

contactdetails:
  email: "dev_support@example.com"  # QA support email
  name: "EazyBytes DEV Team"  # QA team name
  onCallSupport: "9876543210"  # QA support number

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all management endpoints
