spring:
  application:
    name: eureka-server
  cloud:
    config:
      import: optional:configserver:http://localhost:8071/

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8070

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
  serviceUrl:
    defaultZone: http://localhost:8070/eureka
