spring:
  application:
    name: Loans
  datasource:
    url: jdbc:mysql://localhost:3306/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate.dialect:  org.hibernate.dialect.MySQLDialect
    sql:
      init-mode: always

build:
  Loans:
    message: "Hello, Welcome to EazyBytes Accounts realted prod API'S!"
ContactDetails:
  email: "L1H5o@example.com"
  name: "EazyBytes"
  onCallSupport: "1234567890"